Fix node exceptions
C-Accel-CRIPT/Python-SDK pull request #87
Opened 2023-05-02 20:31 UTC by nh916

# Description

## Changes

## Known Issues
*  `CRIPTJsonDeserializationError` docs needs updates down the line
    * more documentation is needed on how to troubleshoot this section
    * better explanation is needed on how and why this error occurs as well as an example of where it would and wouldn't occur

## Screenshots

2023-05-24 22:43 UTC, InnocentBug requested changes
This seems out of sync.

Some changes revert what we added and some exceptions are just missing.
Seems like a rebase from something old, can you check that?

For example the orphan exception are removed for some reason.

2023-05-24 22:43 UTC, InnocentBug commented on src/cript/api/api.py
> -        try:
is it intended to not throw a custom exception here anymore?

2023-05-24 22:43 UTC, InnocentBug commented on src/cript/api/api.py
> -        except jsonschema.exceptions.ValidationError as error:
This error message is superior to the new one.

2023-05-24 22:43 UTC, InnocentBug commented on src/cript/api/api.py
> -        except jsonschema.exceptions.ValidationError as error:
at least raise the exception from the old one.

2023-05-25 00:19 UTC, nh916 commented
closing this PR in favor of the [updated one](https://github.com/C-Accel-CRIPT/Python-SDK/pull/110)

2023-05-25 00:19 UTC, closed without merging